version: '2'

services:
    api:
        build: ./api
        ports:
            - "8080:80"
        env_file:
          - .env
        volumes:
            - ./api:/usr/src/app
        depends_on:
            - db

    db:
        image: postgres:9.6.3
        ports:
            - "5432:5432"
